package org.thesummoners.model.pokemon;

public enum Type {
    WATER, BUG, DRAGON, ELECTRIC, GHOST, FIRE, ICE, FIGHTING, NORMAL, PLANT, PSYCHIC, ROCK, EARTH, POISON, FLYING, GROUND, GRASS, NOTHING, NULL
}
